Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false
